openapi: 3.0.0
info:
  title: API de Manejo de Archivos y Palabras
  version: 1.0.0
  description: Documentación de la API para contar palabras y buscar palabras en archivos.
servers:
  - url: 'http://loacalhost:4000/'

paths:
  /api/file/count-words:
    post:
      summary: Contar palabras en un archivo
      tags:
        - Archivos
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Palabras contadas con éxito en el archivo
        '400':
          description: Error en la solicitud o archivo no proporcionado
        '500':
          description: Error interno del servidor

  /api/file/find-word:
    post:
      summary: Buscar palabra en un archivo
      tags:
        - Archivos
      parameters:
        - in: query
          name: word
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Palabra encontrada con éxito en el archivo
        '400':
          description: Error en la solicitud, archivo no proporcionado o palabra no ingresada
        '500':
          description: Error interno del servidor
